import { StyleSheet } from 'react-native';

import { appTheme } from '../../../theme/app-theme';

export const schoolPhotoGalleryStyles = StyleSheet.create({
  closeIcon: {
    height: 22,
    width: 22,
  },
  countBadge: {
    backgroundColor: appTheme.colors.surfaceAlt,
    borderColor: appTheme.colors.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  countBadgeText: {
    color: appTheme.colors.brandStrong,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyGallery: {
    backgroundColor: appTheme.colors.surfaceAlt,
    borderColor: appTheme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  emptyText: {
    color: appTheme.colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  featuredFooter: {
    alignItems: 'center',
    backgroundColor: 'rgba(7, 31, 29, 0.72)',
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 14,
    paddingVertical: 10,
    position: 'absolute',
    right: 0,
  },
  featuredFooterText: {
    color: appTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: '700',
  },
  featuredImage: {
    backgroundColor: '#061F1D',
    height: '100%',
    width: '100%',
  },
  featuredNavButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(7, 31, 29, 0.72)',
    borderColor: 'rgba(255, 255, 255, 0.34)',
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  featuredNavigation: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 14,
    position: 'absolute',
    right: 14,
    top: '43%',
  },
  featuredPhoto: {
    alignItems: 'center',
    backgroundColor: '#061F1D',
    height: 360,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  galleryPanel: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#0B1F33',
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 18,
  },
  lightboxBackdrop: {
    backgroundColor: 'rgba(2, 15, 16, 0.96)',
    flex: 1,
    paddingBottom: 20,
    paddingHorizontal: 22,
    paddingTop: 18,
  },
  lightboxCloseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  lightboxCounter: {
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  lightboxCounterText: {
    color: appTheme.colors.textInverse,
    fontSize: 13,
    fontWeight: '700',
  },
  lightboxHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingBottom: 16,
  },
  lightboxHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  lightboxImage: {
    height: '100%',
    width: '100%',
  },
  lightboxNavButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderColor: 'rgba(255, 255, 255, 0.24)',
    borderRadius: 999,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    position: 'absolute',
    width: 52,
  },
  lightboxNavIcon: {
    height: 28,
    width: 28,
  },
  lightboxNavLeft: {
    left: 8,
  },
  lightboxNavRight: {
    right: 8,
  },
  lightboxStage: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  lightboxSubtitle: {
    color: 'rgba(255, 255, 255, 0.72)',
    fontSize: 13,
    lineHeight: 20,
  },
  lightboxThumb: {
    borderColor: 'transparent',
    borderRadius: 10,
    borderWidth: 2,
    height: 72,
    opacity: 0.74,
    overflow: 'hidden',
    width: 108,
  },
  lightboxThumbImage: {
    height: '100%',
    width: '100%',
  },
  lightboxThumbRail: {
    flexGrow: 0,
    paddingTop: 16,
  },
  lightboxThumbRailContent: {
    gap: 10,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  lightboxThumbSelected: {
    borderColor: appTheme.colors.textInverse,
    opacity: 1,
  },
  lightboxTitle: {
    color: appTheme.colors.textInverse,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  navigationIcon: {
    height: 24,
    width: 24,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: appTheme.colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  thumbnail: {
    backgroundColor: '#061F1D',
    borderColor: 'transparent',
    borderRadius: 10,
    borderWidth: 2,
    height: 76,
    overflow: 'hidden',
    width: 126,
  },
  thumbnailImage: {
    backgroundColor: '#061F1D',
    height: '100%',
    width: '100%',
  },
  thumbnailRail: {
    flexGrow: 0,
  },
  thumbnailRailContent: {
    gap: 8,
    padding: 10,
  },
  thumbnailSelected: {
    borderColor: appTheme.colors.brandStrong,
  },
});
